### ISSUE TITLE
Extra File Added to the develop branch

### ISSUE THREAD

**Issue by UltimatePea** [UCSDOalads/JavaSketchPad#108]
The following file was accidentally added to the develop branch. Please untracked it from version control.
```
/.java/fonts/1.8.0_121/fcinfo-1-its-cseb260-18.ucsd.edu-null-null-en.properties
```

**Comment by chenggong03** [comment]
Previous file deleted, but now ?/.java/fonts/1.8.0_121 is in develop

**Comment by chenggong03** [comment]
Solved
