### ISSUE TITLE
Undo does not refresh the paint panel until mouse moved

### ISSUE THREAD

**Issue by UltimatePea** [UCSDOalads/JavaSketchPad#24]
When removing a data line segment, and a dataIO, and Undo the action, the paint panel won't refresh

**Comment by chenggong03** [comment]
Reproduction: create an object (say a Display Box) and then remove it. And then, undo and redo actions only takes effects when the mouse moves into the center canvas. They do not take effect when mouse is on History UI.

**Comment by lhwlyd** [comment]
Solved
